global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'inescape-staging'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/v1/metrics'

  - job_name: 'postgres-staging'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis-staging'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'mongodb-staging'
    static_configs:
      - targets: ['mongodb:27017']

