global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'inescape-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'inescape-api'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'

